minimum_pre_commit_version: 2.16.0
default_stages: [commit, push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
        args: ["--maxkb=10000"]
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: trailing-whitespace
  - repo: https://github.com/talos-systems/conform
    rev: v0.1.0-alpha.25
    hooks:
      - id: conform
        stages: [commit-msg]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.62.3
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        always_run: true
        stages: [post-rewrite]
        args:
          - --hook-config=--path-to-file=./README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
          - --args=--config=.config/.terraform-docs.yaml
      - id: terraform_tflint
        args:
          - --args=--config=.config/.tflint.hcl
          - --args=--ignore-module=./examples
      - id: checkov
        args: [
          "-d", ".",
          "--skip-path", "base*",
          "--skip-path", "module*",
          "--skip-path", "logical*",
          "--skip-path", "template*"
        ]
