formatter: "markdown table"

version: ">= 0.16.0, < 1.0.0"

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show:
     - header
     - providers
     - inputs
     - outputs

content: |-
  {{ .Header }}

  ## Dependencies

  {{ .Inputs }}

  {{ .Outputs }}

  ## Providers
  {{ include "./.terraform.lock.hcl" }}

  ## Contribution

  ## Bug Reporting
  {{ include "./.github/ISSUE_TEMPLATE/00-bug-issue.md"}}

  ## Modules

  {{ range .Module.ModuleCalls }}
  - {{ .Name }} ({{ .Position.Filename }}#{{ .Position.Line }})
  {{- end }}

  ## Resources

  {{ range .Module.Resources }}
  - {{ .GetMode }}.{{ .Spec }} ({{ .Position.Filename }}#{{ .Position.Line }})
  {{- end }}

output:
  file: ""
  mode: inject

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: true
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
